### ISSUE TITLE
Compile failure on 5.4.0

### ISSUE THREAD

**Issue by joelsmithTT** [tenstorrent/tt-kmd#49]
```
% cat /var/lib/dkms/tenstorrent/1.31/build/make.log
DKMS make.log for tenstorrent-1.31 for kernel 5.4.0-198-generic (x86_64)
Wed Mar 26 15:07:48 UTC 2025
make: Entering directory '/usr/src/linux-headers-5.4.0-198-generic'
  AR      /var/lib/dkms/tenstorrent/1.31/build/built-in.a
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/module.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/chardev.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/enumerate.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/interrupt.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/grayskull.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/wormhole.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/pcie.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/blackhole.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/hwmon.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/sg_helpers.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/memory.o
  CC [M]  /var/lib/dkms/tenstorrent/1.31/build/tlb.o
/var/lib/dkms/tenstorrent/1.31/build/tlb.c: In function 'tenstorrent_device_allocate_tlb':
/var/lib/dkms/tenstorrent/1.31/build/tlb.c:46:7: error: implicit declaration of function 'signal_pending' [-Werror=implicit-function-declaration]
   46 |   if (signal_pending(current))
      |       ^~~~~~~~~~~~~~
/var/lib/dkms/tenstorrent/1.31/build/memory.c:876:3: error: 'const struct vm_operations_struct' has no member named 'may_split'
  876 |  .may_split = tlb_vma_may_split,
      |   ^~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:270: /var/lib/dkms/tenstorrent/1.31/build/memory.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:270: /var/lib/dkms/tenstorrent/1.31/build/tlb.o] Error 1
make: *** [Makefile:1778: /var/lib/dkms/tenstorrent/1.31/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.4.0-198-generic'
```

Need workarounds for older kernels.

**Comment by alewycky-tenstorrent** [comment]
Before may_split, there was split. It was introduced in 31383c6865a578834dd953d9dbc88e6b19fe3997. dev_dax_split and hugetlb_vm_op_split return errors that block the operation. But it seems to not block all operations, e.g. mremap. 73d5e06299195f4df82832cfc4a3a0c574c1e473 added additional may_split checks at the time when split was renamed to may_split.

So I think
1. implement split for pre-5.11
2. add test case for pre-5.11 that runs a partial mremap and verifies that it doesn't corrupt refcounts
